# Generated by Django 4.2.6 on 2023-10-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardhub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_card_products', models.ManyToManyField(to='cardhub.creditcardproduct')),
            ],
        ),
    ]
