# Generated by Django 4.2.7 on 2023-11-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardhub', '0005_accountstatement_cardholder_cardholdercard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcardproduct',
            name='annuity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
