# Generated by Django 4.2.7 on 2023-11-11 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardhub', '0006_alter_creditcardproduct_annuity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='card_holder',
        ),
        migrations.AddField(
            model_name='cardholder',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cardhub.user'),
        ),
    ]
