# Generated by Django 4.2.7 on 2023-11-11 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardhub', '0007_remove_user_card_holder_cardholder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardholder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardhub.user'),
        ),
    ]
