# Generated by Django 4.2.7 on 2023-11-13 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardhub', '0010_rename_card_accountstatement_card_from_cardholder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountstatement',
            name='current_debt',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='accountstatement',
            name='cut_off_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='accountstatement',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='accountstatement',
            name='payment_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='accountstatement',
            name='payment_for_no_interest',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
